---
- name: Install the latest updates
  yum: 
    name: '*'
    state: latest
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Uninstall conflicting packages
  yum:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - podman
    - buildah