apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: default-primera-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: default-primera-storageclass
