apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: primera-a660-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: primera-a660-storageclass
