apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: tkg-cluster-01
  namespace: hpe-storage
spec:
  distribution:
    version: v1.18.10+vmware.1-tkg.1.3a6cd48
  topology:
    controlPlane:
      count: 1
      class: best-effort-xsmall
      storageClass: primera-default-profile
    workers:
      count: 3
      class: best-effort-xsmall
      storageClass: primera-default-profile
